apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcd-gitops-demo
spec:
  selector:
    matchLabels:
      app: fluxcd-gitops-demo
  template:
    metadata:
      labels:
        app: fluxcd-gitops-demo
    spec:
      imagePullSecrets:
        - name: acr-secret      
      containers:
      - name: fluxcd-gitops-demo
        imagePullPolicy: IfNotPresent
        image: registry.cn-hangzhou.aliyuncs.com/fluxcd-demo/flux-gitops-demo:de4b264df161a5d3eaa1cb9c87a05709ae4a90c9

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
