apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: fluxcd-gitops-demo
  namespace: flux-system
spec:
  image: registry.cn-hangzhou.aliyuncs.com/fluxcd-demo/flux-gitops-demo
  interval: 1m
  secretRef:
    name: acr-secret