apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluxcd-gitops-demo
spec:
  interval: 5s
  path: /app
  prune: true
  sourceRef:
    # 需要定义 但实际监听仓库tag时无用
    kind: GitRepository
    name: fluxcd-gitops-demo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: fluxcd-gitops-demo
      namespace: flux-system