apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1oYW5nemhvdS5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiI0Mzg3ODk2NDNAcXEuY29tIiwicGFzc3dvcmQiOiJBZG1pbjEyM0Bhc2NtIiwiYXV0aCI6Ik5ETTROemc1TmpRelFIRnhMbU52YlRwQlpHMXBiakV5TTBCaGMyTnQifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: acr-secret
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
